name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: mkdir
      run: |
        mkdir ./dist
        zip -r ./dist/my-react-sample.zip /home/runner/work/my-react-sample/

    - name: Run a one-line script
      run: echo Hello World.

    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
